sass:
  style: compressed
repository: https://github.com/mattstillson.github.io
timezone: America/New_York
future: true
jailed: false
theme: jekyll-theme-cayman

name: Matt Stillson Production Engineer.
description: Developer and Guru with multiple Software
url: Matthew Stillson

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - CNAME
